Setup Workflows

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,97 +1,165 @@
-# GitHub Actions Workflow created for handling the release process based on the draft release prepared
-# with the Build workflow. Running the publishPlugin task requires the PUBLISH_TOKEN secret provided.
-
 name: Release
+
 on:
-  release:
-    types: [prereleased, released]
+  push:
+    branches: [ master ]
+
+permissions:
+  contents: write
+  pull-requests: write
 
 jobs:
-
-  # Prepare and publish the plugin to the Marketplace repository
-  release:
-    name: Publish Plugin
+  check_code: # Validates the code
     runs-on: ubuntu-latest
-    permissions:
-      contents: write
-      pull-requests: write
     steps:
+    - uses: actions/checkout@v4
+      
+    - name: Set up JDK
+      uses: actions/setup-java@v4
+      with:
+        java-version: '17'
+        distribution: 'temurin'
+        cache: 'gradle'
+      
+    - name: Build
+      run: ./gradlew build buildPlugin --info
+      
+    - name: Check for uncommited changes
+      run: |
+        if [[ "$(git status --porcelain)" != "" ]]; then
+          echo ----------------------------------------
+          echo git status
+          echo ----------------------------------------
+          git status
+          echo ----------------------------------------
+          echo git diff
+          echo ----------------------------------------
+          git diff
+          echo ----------------------------------------
+          echo Troubleshooting
+          echo ----------------------------------------
+          echo "::error::Unstaged changes detected. Locally try running: git clean -ffdx && mvn -B clean package"
+          exit 1
+        fi
 
-      # Check out current repository
-      - name: Fetch Sources
-        uses: actions/checkout@v3
-        with:
-          ref: ${{ github.event.release.tag_name }}
+  prepare_release:
+    runs-on: ubuntu-latest
+    needs: [check_code]
+    outputs:
+      upload_url: ${{ steps.create_release.outputs.upload_url }}
+    steps:
+    - uses: actions/checkout@v4
+      
+    - name: Configure Git
+      run: |
+        git config --global user.email "actions@github.com"
+        git config --global user.name "GitHub Actions"
+      
+    - name: UN-Snap version and output
+      id: version
+      run: |
+        originalVersion=$(grep -Po 'pluginVersion=\K.*' gradle.properties)
+        newVersion="$(echo $originalVersion | cut -d '-' -f1)"
+        echo "New version: $newVersion"
+        sed -i "s/pluginVersion=$originalVersion/pluginVersion=$newVersion/" gradle.properties
+        
+        version=$newVersion
+        echo "release=$version" >> $GITHUB_OUTPUT
+        echo "releasenumber=${version//[!0-9]/}" >> $GITHUB_OUTPUT
 
-      # Setup Java 11 environment for the next steps
-      - name: Setup Java
-        uses: actions/setup-java@v3
-        with:
-          distribution: zulu
-          java-version: 11
+        echo "Contents of gradle.properties"
+        cat gradle.properties
+  
+    - name: Commit and Push
+      run: |
+        git add -A
+        git commit -m "Release ${{ steps.version.outputs.release }}"
+        git push origin
+        git tag v${{ steps.version.outputs.release }}
+        git push origin --tags
+    
+    - name: Create Release
+      id: create_release
+      uses: shogo82148/actions-create-release@v1
+      with:
+        tag_name: v${{ steps.version.outputs.release }}
+        release_name: v${{ steps.version.outputs.release }}
+        commitish: master
+        body: |
+          ## [Changelog](https://github.com/xdev-software/${{ github.event.repository.name }}/blob/develop/CHANGELOG.md#${{ steps.version.outputs.releasenumber }})
+          See [Changelog#v${{ steps.version.outputs.release }}](https://github.com/xdev-software/${{ github.event.repository.name }}/blob/develop/CHANGELOG.md#${{ steps.version.outputs.releasenumber }}) for more information.
 
-      # Set environment variables
-      - name: Export Properties
-        id: properties
-        shell: bash
-        run: |
-          CHANGELOG="$(cat << 'EOM' | sed -e 's/^[[:space:]]*$//g' -e '/./,$!d'
-          ${{ github.event.release.body }}
-          EOM
-          )"
+          ## Installation
+          The plugin is listed on the [Marketplace](https://plugins.jetbrains.com/plugin/22113).
           
-          CHANGELOG="${CHANGELOG//'%'/'%25'}"
-          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
-          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
-
-          echo "::set-output name=changelog::$CHANGELOG"
-
-      # Update Unreleased section with the current release note
-      - name: Patch Changelog
-        if: ${{ steps.properties.outputs.changelog != '' }}
-        env:
-          CHANGELOG: ${{ steps.properties.outputs.changelog }}
-        run: |
-          ./gradlew patchChangelog --release-note="$CHANGELOG"
-
-      # Publish the plugin to the Marketplace
-      - name: Publish Plugin
-        env:
-          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
-          CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
-          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
-          PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
-        run: ./gradlew publishPlugin
-
-      # Upload artifact as a release asset
-      - name: Upload Release Asset
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: gh release upload ${{ github.event.release.tag_name }} ./build/distributions/*
-
-      # Create pull request
-      - name: Create Pull Request
-        if: ${{ steps.properties.outputs.changelog != '' }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          VERSION="${{ github.event.release.tag_name }}"
-          BRANCH="changelog-update-$VERSION"
-          LABEL="release changelog"
-
-          git config user.email "action@github.com"
-          git config user.name "GitHub Action"
-
-          git checkout -b $BRANCH
-          git commit -am "Changelog update - $VERSION"
-          git push --set-upstream origin $BRANCH
+          Open the plugin Marketplace in your IDE (``File > Settings > Plugins > Marketplace``), search for the plugin and hit the install button.
           
-          gh label create "$LABEL" \
-            --description "Pull requests with release changelog update" \
-            || true
+          Alternatively you can also download the jar from the marketplace website.
 
-          gh pr create \
-            --title "Changelog update - \`$VERSION\`" \
-            --body "Current pull request contains patched \`CHANGELOG.md\` file for the \`$VERSION\` version." \
-            --label "$LABEL" \
-            --head $BRANCH
+  publish:
+    runs-on: ubuntu-latest
+    needs: [prepare_release]
+    steps:
+    - uses: actions/checkout@v4
+    
+    - name: Set up JDK
+      uses: actions/setup-java@v4
+      with:
+        distribution: 'temurin'
+        java-version: 17
+        cache: 'gradle'
+    
+    - name: Init Git and pull
+      run: |
+        git config --global user.email "actions@github.com"
+        git config --global user.name "GitHub Actions"
+        git pull
+    
+    - name: Publish Plugin
+      env:
+        PUBLISH_TOKEN: ${{ secrets.JETBRAINS_MARKETPLACE_PUBLISH_TOKEN }}
+        CERTIFICATE_CHAIN: ${{ secrets.JETBRAINS_MARKETPLACE_CERTIFICATE_CHAIN }}
+        PRIVATE_KEY: ${{ secrets.JETBRAINS_MARKETPLACE_PRIVATE_KEY }}
+        PRIVATE_KEY_PASSWORD: ${{ secrets.JETBRAINS_MARKETPLACE_PRIVATE_KEY_PASSWORD }}
+      run: ./gradlew publishPlugin --info --stacktrace
+
+    - name: Upload plugin files
+      uses: actions/upload-artifact@v4
+      with:
+        name: plugin-files
+        path: build/distributions/*
+
+  after_release:
+    runs-on: ubuntu-latest
+    needs: [publish]
+    steps:
+    - uses: actions/checkout@v4
+      
+    - name: Init Git and pull
+      run: |
+        git config --global user.email "actions@github.com"
+        git config --global user.name "GitHub Actions"
+        git pull
+        
+    - name: Inc Version and SNAP root
+      run: |
+        originalVersion=$(grep -Po 'pluginVersion=\K.*' gradle.properties)
+        newVersion="$(echo $originalVersion | cut -d '-' -f1 | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{$NF=sprintf("%0*d", length($NF), ($NF+1)); print}')-SNAPSHOT"
+        echo "New version: $newVersion"
+        sed -i "s/pluginVersion=$originalVersion/pluginVersion=$newVersion/" gradle.properties
+        
+        echo "Contents of gradle.properties"
+        cat gradle.properties
+
+    - name: Git Commit and Push
+      run: |
+        git add -A
+        git commit -m "Preparing for next development iteration"
+        git push origin
+    
+    - name: pull-request
+      uses: repo-sync/pull-request@v2
+      with:
+        destination_branch: "develop"
+        pr_title: "Sync back"
+        pr_body: "An automated PR to sync changes back"
